The name of file is "MakeFile"
If you want to run or update a task when certain files are updated, the make utility can come in handy.

example:
#Link:https://opensource.com/article/18/8/what-how-makefile

.PHONY:all say_hello generate clean
all:say_hello generate
#.DEFAULT_GOAL:=generate #specify function to execute else all function execute`

say_hello:
        @echo "Hello World!" #use '@' to prevent echoing of command

generate:
        @echo "Creating empty text files..."
        touch file-{1..10}.txt

clean:
        @echo "Cleaning up..."
        rm *.txt
